### PR TITLE
Make it possible to include the SDK in the darwin container.

### PR DESCRIPTION
**Pull request by Bluebugs**
### Description:
When running fyne-cross with k8s, it is more efficient to build an image that include the SDK. This patch make it possible for fyne-cross to assume the SDK was packaged in the container.

### Checklist:
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by lucor — COMMENTED** [review]
Makes sense to me.
What about adding a special value for the existing flag `sdk-path` like `bundled` or `included`. In theory we could also by default check for a bundled SDK before return an error. What do you think?

**Comment by andydotxyz** [comment]
> In theory we could also by default check for a bundled SDK before return an error. What do you think?

I agree with this - even the new flag docs imply that it is an indication rather than a specified location. So why not just check if it exists before mounting an external location and/or erroring because one was not specified?

**Comment by Bluebugs** [comment]
I am not to sure how you would check the existence of a file inside the container, any suggestion?

**Comment by andydotxyz** [comment]
> I am not to sure how you would check the existence of a file inside the container, any suggestion?

I don't have a specific suggestion - it was just an idea. 
If it cannot be done then @lucor suggestion seems like a great one.

**Comment by Bluebugs** [comment]
> `docker run ... fyneio/fyne-cross-images:darwin sh -c 'ls /sdk/path/to/file'` and check for the error

That's working, nice!

**Review by lucor — APPROVED** [review]
I'd add a comment to describe the objective of the ls command. Apart that looks good to me

**Comment by Bluebugs** [comment]
Comment added!

**Review by andydotxyz — APPROVED** [review]
Nice

**Review by lucor — APPROVED** [review]
Great, thanks!

**Pull request merged**
