### PR TITLE
Add support for creating packaged .tar.gz bundles on freebsd

### LINKED ISSUE #4: Add support for creating packaged .tar.gz bundles on freebsd
Currently, only binaries are built when cross-compiling for `freebsd`. The support for running the `package` command in `fyne.io/fyne/cmd/fyne` landed in `v1.4.0`. It would be great if we could update to support this.

### PR DESCRIPTION
**Pull request by lucor**
This PR add support for creating packaged .tar.gz bundles on freebsd

Fixes #4

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
Hmm, I am seeing a few errors when trying to build for freebsd using this. The following output is what I am seeing:
```
~/go/bin/fyne-cross freebsd -arch amd64 -app-id com.github.jacalz.wormhole-gui -icon internal/assets/icon/icon-512.png
[i] Target: freebsd/amd64
[i] Cleaning target directories...
[✓] "temp" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/tmp/freebsd-amd64
[✓] "bin" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/bin/freebsd-amd64
[✓] "dist" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/dist/freebsd-amd64
[i] Checking for go.mod: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/go.mod
[✓] go.mod found
[i] Building binary...
# github.com/go-gl/glfw/v3.3/glfw
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/native_linbsd.go:10:
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/glfw/include/GLFW/glfw3native.h:114:
In file included from /freebsd/usr/local/include/GL/glx.h:32:
/freebsd/usr/local/include/GL/gl.h:61:11: warning: 'GLAPIENTRY' macro redefined [-Wmacro-redefined]
/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/glfw/include/GLFW/glfw3.h:5863:10: note: previous definition is here
[✓] Binary: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/bin/freebsd-amd64/wormhole-gui
[i] Packaging app...
unsupported target operating system "freebsd"
[✗] could not package the Fyne app: could not package the Fyne app: exit status 1
make: *** [Makefile:42: freebsd] Error 1
```

**Comment by lucor** [comment]
Hmm, just wondering if something is not up-to-date. 
Could you please confirm that fyne-cross is compiled from `github.com/lucor/fyne-io-fyne-cross@feature/freebsd-package` and docker image hash for `fyneio/fyne-cross:freebsd-latest` is `sha256:425c28439c36a64a1ed7559add02bed9c88c26003a6182eded0261fa64cf5f7e`?

For comparison below the output in debug mode on my linux box:
```
fyne-cross freebsd -arch amd64 -app-id com.github.jacalz.wormhole-gui -icon internal/assets/icon/icon-512.png -debug
[i] Target: freebsd/amd64
command.Context{Volume:volume.Volume{binDirHost:"/code/lucor/wormhole-gui/fyne-cross/bin", cacheDirHost:"/home/lucor/.cache/fyne-cross", distDirHost:"/code/lucor/wormhole-gui/fyne-cross/dist", tmpDirHost:"/code/lucor/wormhole-gui/fyne-cross/tmp", workDirHost:"/code/lucor/wormhole-gui"}, Architecture:"amd64", Env:[]string{"GOOS=freebsd", "GOARCH=amd64", "CC=x86_64-unknown-freebsd11-clang"}, ID:"freebsd-amd64", LdFlags:[]string(nil), OS:"freebsd", Tags:[]string(nil), AppID:"com.github.jacalz.wormhole-gui", CacheEnabled:true, DockerImage:"fyneio/fyne-cross:freebsd-latest", Icon:"internal/assets/icon/icon-512.png", Output:"wormhole-gui", Package:".", StripDebug:true, Debug:true, Pull:false}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /code/lucor/wormhole-gui/fyne-cross/bin/freebsd-amd64
[✓] "dist" dir cleaned: /code/lucor/wormhole-gui/fyne-cross/dist/freebsd-amd64
[✓] "temp" dir cleaned: /code/lucor/wormhole-gui/fyne-cross/tmp/freebsd-amd64
[i] Checking for go.mod: /code/lucor/wormhole-gui/go.mod
[✓] go.mod found
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /code/lucor/wormhole-gui:/app -v /home/lucor/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=freebsd -e GOARCH=amd64 -e CC=x86_64-unknown-freebsd11-clang -e fyne_uid=1000 fyneio/fyne-cross:freebsd-latest go build -ldflags '-w -s' -o /app/fyne-cross/bin/freebsd-amd64/wormhole-gui -v .
# github.com/go-gl/glfw/v3.3/glfw
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/native_linbsd.go:10:
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/glfw/include/GLFW/glfw3native.h:114:
In file included from /freebsd/usr/local/include/GL/glx.h:32:
/freebsd/usr/local/include/GL/gl.h:61:11: warning: 'GLAPIENTRY' macro redefined [-Wmacro-redefined]
/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/glfw/include/GLFW/glfw3.h:5863:10: note: previous definition is here
[✓] Binary: /code/lucor/wormhole-gui/fyne-cross/bin/freebsd-amd64/wormhole-gui
[i] Packaging app...
/usr/bin/docker run --rm -t -w /app -v /code/lucor/wormhole-gui:/app -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 fyneio/fyne-cross:freebsd-latest /usr/local/bin/fyne version
fyne cli version v1.4.0
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/freebsd-amd64 -v /code/lucor/wormhole-gui:/app -v /home/lucor/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 fyneio/fyne-cross:freebsd-latest /usr/local/bin/fyne package -os freebsd -name wormhole-gui -icon /app/fyne-cross/tmp/freebsd-amd64/Icon.png -appID com.github.jacalz.wormhole-gui -executable /app/fyne-cross/bin/freebsd-amd64/wormhole-gui
[✓] Package: /code/lucor/wormhole-gui/fyne-cross/dist/freebsd-amd64/wormhole-gui.tar.gz
```

**Comment by Jacalz** [comment]
Looks like my docker image was too old. Running `fyne-cross freebsd -pull` solved it. Couldn't `fyne-cross` check if images are too old and then automatically pull a new one?

**Review by Jacalz — APPROVED** [review]
Looks good to me. Thanks for adding this :+1:

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
Thanks. I think you should be able to merge this now @lucor?

**Pull request merged**
