### PR TITLE
Update docker images: Go v1.17 and Android builds SDK 30 

### PR DESCRIPTION
**Pull request by lucor**
This PR updates the `android` docker image to use the latest command line tools and updates the Android builds to SDK 30

### CODE REVIEW

**Comment by Jacalz** [comment]
I'm wondering if we perhaps should wait a little bit more before jumping onto 1.17. Not that I have used it yet and/or found any breaking bugs, but it might be worth waiting for one or two bug fixes before we make the change. It also lets the rest of the ecosystem catch up a bit (if it needs to).

It would also be nice if we could get Windows/arm64 support in but I don't have any machine to run that so I'll not personally shout it out as a priority :)

**Review by andydotxyz — DISMISSED** [review]
Cool :)

**Review by andydotxyz — APPROVED** [review]
Yeah, Jacob's point is a good one

**Comment by lucor** [comment]
@Jacalz it is a good point. Yes, the idea was to add support for windows/arm64 as well but let's remove the Go 1.17 update from this PR (done in 0615997) and handle later with a dedicated one :)

**Review by Jacalz — APPROVED** [review]
Sounds good 👍

**Pull request merged**
