### PR TITLE
add libasound2 for all linux docker images

### LINKED ISSUE #95: Problems building for linux arm on debian (music, alsa, touch)
I want to build a fyne app for a smart home usecase on a debian bullseye virtual machine. The target device is an embedded device with a connected touch panel with linux debian operating system and arm architecture.  
## Problem 1: Cross-compiling when using alsa
I use the library https://github.com/faiface/beep to play mp3 music and in the virtual machine it works fine. But when I try to cross compile with fyne-cross, I get an error that alsa is missing.
I already tried to manually add ```libasound2-dev:armhf``` in the docker container, but it did not work. Do you have any suggestions or ideas how to fix the problem?

### Describe the bug:

Fyne-cross compiling results in an error. I use the following command:  
```fyne-cross linux -arch arm```
And the output is the following:
[i] Target: linux/arm
[i] Cleaning target directories...
[✓] "temp" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/tmp/linux-arm
[✓] "bin" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/bin/linux-arm
[✓] "dist" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/dist/linux-arm
[i] Checking for go.mod: /home/devel/Dokumente/smart-home/go.mod
[✓] go.mod found
[i] Building binary...
\# pkg-config --cflags  -- alsa
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
pkg-config: exit status 1
[✗] exit status 2

### Example code: (just using the faiface/beep library)

       func Play() {
	       
	       f, err := os.Open("music.mp3")
	       if err != nil {
		        log.Fatalln(err)
	       }

	       streamer, format, err := mp3.Decode(f)
	       if err != nil {
		        log.Fatalln(err)
	       }
	       speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
	       speaker.Play(streamer)

      }

### Device and debug info

<summary>Device info</summary>

 - **OS:**  Linux 
 - **Version:**  Debian GNU/Linux 11 (bullseye)
 - **Go version:**  1.18
 - **fyne-cross version:**  1.2.0
 - **Fyne version:**  2.1.3 

<details><summary>Debug info</summary><br><pre>

[i] Target: linux/arm
command.Context{Volume:volume.Volume{binDirHost:"/home/devel/Dokumente/smart-home/fyne-cross/bin", cacheDirHost:"/home/devel/.cache/fyne-cross", distDirHost:"/home/devel/Dokumente/smart-home/fyne-cross/dist", tmpDirHost:"/home/devel/Dokumente/smart-home/fyne-cross/tmp", workDirHost:"/home/devel/Dokumente/smart-home"}, Architecture:"arm", Env:[]string{"GOOS=linux", "GOARCH=arm", "CC=arm-linux-gnueabihf-gcc", "GOARM=7"}, ID:"linux-arm", LdFlags:[]string(nil), OS:"linux", Tags:[]string{"gles"}, AppBuild:"1", AppID:"", AppVersion:"1.0", CacheEnabled:false, DockerImage:"docker.io/fyneio/fyne-cross:1.2-linux-arm", Icon:"/home/devel/Dokumente/smart-home/Icon.png", Name:"smart-home", Package:".", Release:false, StripDebug:true, Debug:true, Pull:false, Category:"", Certificate:"", Developer:"", Keystore:"", KeystorePass:"", KeyPass:"", Password:"", Profile:""}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/bin/linux-arm
[✓] "dist" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/dist/linux-arm
[✓] "temp" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/tmp/linux-arm
[i] Checking for go.mod: /home/devel/Dokumente/smart-home/go.mod
[✓] go.mod found
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /home/devel/Dokumente/smart-home:/app:z -u 1001:1001 --entrypoint fixuid -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=linux -e GOARCH=arm -e CC=arm-linux-gnueabihf-gcc -e GOARM=7 -e CGO_LDFLAGS=-w -s docker.io/fyneio/fyne-cross:1.2-linux-arm go build -trimpath -tags 'gles' -o /app/fyne-cross/bin/linux-arm/smart-home -v .
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: updating user 'docker' to UID '1001'
fixuid: updating group 'docker' to GID '1001'
fixuid: recursively searching path /
fixuid: chown /home/docker
fixuid: chown /home/docker/.bash_logout
fixuid: chown /home/docker/.bashrc
fixuid: chown /home/docker/.profile
go: downloading fyne.io/fyne/v2 v2.1.3
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/godbus/dbus/v5 v5.0.4
go: downloading golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: downloading github.com/wcharczuk/go-chart/v2 v2.1.0
go: downloading gorm.io/driver/sqlite v1.3.1
go: downloading gorm.io/gorm v1.23.2
go: downloading github.com/hajimehoshi/go-mp3 v0.3.0
go: downloading github.com/hajimehoshi/oto v0.7.1
go: downloading github.com/robtec/newsapi v0.0.0-20180922142248-e986ded8a669
go: downloading github.com/bpicode/fritzctl v1.4.23
go: downloading github.com/yuin/goldmark v1.3.8
go: downloading github.com/fredbi/uri v0.0.0-20181227131451-3dcfdacbaaf3
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20211024062804-40e447a793be
go: downloading github.com/mattn/go-sqlite3 v1.14.9
go: downloading github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
go: downloading golang.org/x/image v0.0.0-20200927104501-e162460cd6b5
go: downloading github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff
go: downloading github.com/srwiley/oksvg v0.0.0-20200311192757-870daf9aa564
go: downloading github.com/srwiley/rasterx v0.0.0-20200120212402-85cb7272f5e9
go: downloading github.com/go-gl/gl v0.0.0-20210813123233-e4099ee2221f
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/jinzhu/now v1.1.4
go: downloading golang.org/x/net v0.0.0-20210813160813-60bc85c4be6d
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/fatih/color v1.13.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/mattn/go-colorable v0.1.9
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading golang.org/x/text v0.3.6
internal/unsafeheader
internal/goexperiment
internal/abi
internal/cpu
runtime/internal/sys
internal/race
sync/atomic
unicode
runtime/internal/math
internal/bytealg
runtime/internal/atomic
unicode/utf8
internal/itoa
math/bits
image/color
math
runtime
container/list
crypto/internal/subtle
crypto/subtle
unicode/utf16
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
vendor/golang.org/x/crypto/internal/subtle
encoding
fyne.io/fyne/v2/internal/color
golang.org/x/image/colornames
golang.org/x/net/html/atom
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/internal/utf8internal
golang.org/x/image/math/f64
golang.org/x/sys/internal/unsafeheader
github.com/bpicode/fritzctl/internal/stringutils
github.com/hajimehoshi/go-mp3/internal/bits
github.com/wcharczuk/go-chart/v2/roboto
github.com/hajimehoshi/go-mp3/internal/imdct
internal/reflectlite
sync
internal/testlog
math/rand
internal/singleflight
runtime/cgo
errors
sort
io
strconv
internal/oserror
syscall
bytes
strings
reflect
bufio
internal/syscall/unix
time
internal/syscall/execenv
path
image
internal/poll
io/fs
hash
hash/crc32
context
crypto
crypto/elliptic/internal/fiat
os
crypto/internal/randutil
crypto/hmac
internal/fmtsort
encoding/binary
crypto/rc4
vendor/golang.org/x/net/dns/dnsmessage
vendor/golang.org/x/crypto/hkdf
vendor/golang.org/x/text/transform
crypto/cipher
crypto/sha512
fmt
io/ioutil
crypto/aes
crypto/des
crypto/ed25519/internal/edwards25519/field
crypto/md5
crypto/sha1
crypto/ed25519/internal/edwards25519
crypto/sha256
encoding/base64
net
log
compress/flate
math/big
encoding/hex
encoding/pem
net/url
compress/gzip
path/filepath
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/crypto/chacha20poly1305
vendor/golang.org/x/crypto/curve25519
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/norm
crypto/rand
crypto/elliptic
encoding/asn1
crypto/ed25519
crypto/rsa
vendor/golang.org/x/crypto/cryptobyte
crypto/dsa
crypto/x509/pkix
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/net/http2/hpack
vendor/golang.org/x/net/idna
crypto/ecdsa
mime
mime/quotedprintable
net/http/internal
net/http/internal/ascii
regexp/syntax
encoding/json
image/internal/imageutil
image/draw
encoding/xml
regexp
golang.org/x/image/math/fixed
crypto/x509
net/textproto
vendor/golang.org/x/net/http/httpproxy
github.com/fredbi/uri
github.com/goki/freetype/raster
vendor/golang.org/x/net/http/httpguts
mime/multipart
golang.org/x/image/font
golang.org/x/image/vector
golang.org/x/net/html
github.com/goki/freetype/truetype
github.com/srwiley/rasterx
crypto/tls
golang.org/x/text/transform
golang.org/x/text/internal/tag
golang.org/x/text/internal/language
golang.org/x/text/encoding
golang.org/x/text/encoding/internal
golang.org/x/text/runes
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
golang.org/x/text/encoding/unicode
golang.org/x/text/internal/language/compact
golang.org/x/image/draw
net/http/httptrace
image/jpeg
golang.org/x/text/language
net/http
hash/adler32
compress/zlib
image/png
golang.org/x/text/encoding/htmlindex
golang.org/x/net/html/charset
github.com/srwiley/oksvg
github.com/go-gl/gl/v3.1/gles2
github.com/goki/freetype
github.com/yuin/goldmark/util
github.com/go-gl/glfw/v3.3/glfw
fyne.io/fyne/v2
fyne.io/fyne/v2/internal/cache
fyne.io/fyne/v2/internal/driver
fyne.io/fyne/v2/internal/app
fyne.io/fyne/v2/storage/repository
fyne.io/fyne/v2/storage
fyne.io/fyne/v2/canvas
fyne.io/fyne/v2/driver/desktop
fyne.io/fyne/v2/theme
fyne.io/fyne/v2/internal/widget
fyne.io/fyne/v2/internal
fyne.io/fyne/v2/internal/animation
fyne.io/fyne/v2/internal/async
fyne.io/fyne/v2/internal/painter
fyne.io/fyne/v2/internal/repository
fyne.io/fyne/v2/layout
fyne.io/fyne/v2/data/binding
fyne.io/fyne/v2/driver/mobile
golang.org/x/sys/unix
github.com/fsnotify/fsnotify
os/exec
os/user
github.com/godbus/dbus/v5
golang.org/x/sys/execabs
github.com/golang/freetype/raster
github.com/yuin/goldmark/text
github.com/yuin/goldmark/ast
github.com/golang/freetype/truetype
github.com/yuin/goldmark/parser
github.com/yuin/goldmark/renderer
github.com/yuin/goldmark/renderer/html
github.com/wcharczuk/go-chart/v2/drawing
github.com/wcharczuk/go-chart/v2/matrix
github.com/yuin/goldmark
github.com/wcharczuk/go-chart/v2
fyne.io/fyne/v2/widget
database/sql/driver
fyne.io/fyne/v2/container
database/sql
go/token
go/scanner
go/ast
github.com/mattn/go-sqlite3
gorm.io/gorm/clause
gorm.io/gorm/utils
gorm.io/gorm/logger
encoding/gob
github.com/jinzhu/inflection
github.com/jinzhu/now
gorm.io/gorm/schema
gorm.io/gorm
gorm.io/gorm/callbacks
gorm.io/gorm/migrator
smart-home/services/weather
github.com/bpicode/fritzctl/internal/errors
github.com/mattn/go-isatty
github.com/mattn/go-colorable
github.com/fatih/color
golang.org/x/crypto/ssh/terminal
github.com/bpicode/fritzctl/logger
gopkg.in/yaml.v2
github.com/bpicode/fritzctl/internal/console
encoding/csv
github.com/bpicode/fritzctl/httpread
github.com/hajimehoshi/go-mp3/internal/consts
github.com/hajimehoshi/go-mp3/internal/frameheader
github.com/hajimehoshi/go-mp3/internal/huffman
github.com/hajimehoshi/go-mp3/internal/sideinfo
github.com/hajimehoshi/go-mp3/internal/maindata
github.com/hajimehoshi/go-mp3/internal/frame
github.com/hajimehoshi/go-mp3
github.com/bpicode/fritzctl/config
github.com/hajimehoshi/oto/internal/mux
github.com/hajimehoshi/oto
# pkg-config --cflags  -- alsa
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
pkg-config: exit status 1
github.com/robtec/newsapi/api
github.com/bpicode/fritzctl/fritz
smart-home/services/news
smart-home/services/fritzbox
fyne.io/fyne/v2/internal/painter/gl
fyne.io/fyne/v2/internal/driver/common
fyne.io/fyne/v2/internal/driver/glfw
fyne.io/fyne/v2/app
gorm.io/driver/sqlite
smart-home/services/clock
smart-home/database
[✗] exit status 2

</pre></details>

## Problem 2: Touch on touch-panel is not working within the application
By omitting the music playback feature and thus not using faiface/beep and alsa, I can cross-compile for my target device and also execute the application on it. Although the touch does work on the system and thus on other applications, the problem is that the touch does not work in the fyne application. The target device uses wayland-weston. In addition, the application only starts when a mouse is plugged in. The same problem does not occur on an android device. Maybe the problem is that for linux/arm compilations the desktop driver gets choosen and there is no touch driver like there is for android devices. Do you have any ideas to fix this problem to enable the touch?

### Describe the bug:
I get the following error output, when running the program on my target device:

image

## Problem 3: Little bug in -tags usage
For the problem before I used the following command:
```fyne-cross linux -arch arm -tags wayland,gles,mesa```
To be able to use this command, I had to use fyne-cross version 1.1.0, because the usage of the version 1.2.0 leads in the error:
[i] Target: linux/arm
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/bin/linux-arm
[✓] "dist" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/dist/linux-arm
[✓] "temp" dir cleaned: /home/devel/Dokumente/smart-home/fyne-cross/tmp/linux-arm
[i] Checking for go.mod: /home/devel/Dokumente/smart-home/go.mod
[✓] go.mod found
[i] Building binary...
cmd/go: -tags space-separated list contains comma
[✗] exit status 2

But when I display the help menu in the command line (```fyne-cross linux -arch arm --help```) it says for the desription of the -tags: ```List of additional build tags separated by comma```.
Is this meant to be like this or a bug? And how am I supposed to execute my command in version 1.2.0?

### PR DESCRIPTION
**Pull request by luisaodh**
### Description:

Added libasound2 to all linux Dockerfiles

Fixes #95

### CODE REVIEW

**Review by Jacalz — COMMENTED** [review]
I appreciate the PR but I don’t think this is the right solution to your problem. As I mentioned in the issue, the intended way is to specify a custom image using the  `-image` flag. Adding dependencies for niece use cases is just going to make the image bigger with little to no gain for the majority of people. I’m sorry, but that’s my opinion on the matter.

I guess the right solution would be to make it easier to specify package that should be installed into the image afterwards but I don’t know how feasible that is.

**Comment by lucor** [comment]
> I appreciate the PR but I unfortunately don’t think this is the right solution to your problem. As I mentioned in the issue, the intended way is to specify a custom image using the -image flag. Adding dependencies for niece use cases is just going to make the image bigger with little to no gain for the majority of people. I’m sorry, but that’s my opinion on the matter.

I agree. IMO libraries shipped into the base images should be the one supported directly by the Fyne APIs. 
As side note probably we should document somewhere how to create and use a custom Docker image.

**Comment by lucor** [comment]
> I guess the right solution would be to make it easier to specify package that should be installed into the image afterwards but I don’t know how feasible that is.

Do you all think that having  fyne-cross to accept a list of dependencies from a file and build automatically the custom image would be helpful or the `-image` flag is good enough ?

I was thinking about something like:

`fyne-cross -image-deps deps.txt -image custom-image linux`

where `deps.txt` contains a list of the additional dependencies to install

**Comment by Bluebugs** [comment]
> `fyne-cross -image-deps deps.txt -image custom-image linux`
> 
> where `deps.txt` contains a list of the additional dependencies to install

It might be a bit more complex than a text file as I think we need to handle a way to specify things for a multitude of OS and platform. Maybe a yaml file will have more flexibility here.

I can imagine:

```
linux:
  deb:
    arm64:
      - gles
    amd64:
      - gl
  rpm:
    arm64:
      - gles
  arch:
    - mesa

darwin:
  deb:
    - gl
```

I know that rpm and arch are not a platform we support at the moment, but I feel like not building with the ability to extend things will be limiting.

**Comment by andydotxyz** [comment]
If these are dependencies of the application I would suggest that perhaps this should be considered in `FyneApp.toml` instead of a fyne-cross specific metadata. That way installers and other tools will know if it can be installed, and we can generate things like `deb` packages.

**Comment by andydotxyz** [comment]
I made a feature request #118 that better reflects the desire to have the flexibility described above.
Closing this PR as being too specific.

**Pull request closed without merging**
