### PR TITLE
[base-image] release 22.10.18

### PR DESCRIPTION
**Pull request by lucor**
### Description:

This PR release the docker base images on docker hub to have them generally available.

#### Release 22.10.18
- Update Go to v1.18.7

#### Images
The following images have been tagged and released on docker hub for testing:
```
1.3-android-22.10.18
1.3-base-22.10.18
1.3-base-freebsd-22.10.18
1.3-base-llvm-22.10.18
1.3-freebsd-amd64-22.10.18
1.3-freebsd-arm64
1.3-freebsd-arm64-22.10.18
1.3-linux-386-22.10.18
1.3-linux-arm-22.10.18
1.3-linux-arm64-22.10.18
1.3-web-22.10.18
1.3-windows-22.10.18
```

> Note: the `latest` tag will tagged and pushed to docker hub as usual once approved

### CODE REVIEW

**Comment by Bluebugs** [comment]
I am a bit confused how this work. I would expect a change in the base Dockerfile to upgrade the go version there, but this PR seems to only change the Changelog file. I think I am missing something.

**Comment by Jacalz** [comment]
> I am a bit confused how this work. I would expect a change in the base Dockerfile to upgrade the go version there, but this PR seems to only change the Changelog file. I think I am missing something.

Look at the commit history on develop. I have already updated the Go version a while ago :)

**Comment by lucor** [comment]
This is still and unfortunately a manual process :( 
I'll try to highlight below the main steps.

The `fyne-cross` tool internally references and uses always the `latest` tag of the base images.
When we are ready to release a new set of base images (i.e. an updated Go version) we build locally, tag and push on docker hub the images with the `release` tag for testing:
- `make build-images`
- `make tag-images`
- `make push-tag-images`

Then a PR is opened asking for feedback and approval. Once approved the `release` images are tagged as `latest` and pushed on docker hub using the following commands:

- `make push-latest-images` 

> Note: the idea was to have a CI/CD for the images once the docker codebase will be moved to its repo https://github.com/fyne-io/fyne-cross-images

**Comment by lucor** [comment]
As @Jacalz said above the changes to updating the Go version were done some days ago, but didn't had a chance to update the docker images until today :-( 
Anyway this was one of the main reasons we decided to move the docker images into a dedicated repo: decouple from the fyne-cross repo and have finally a CI/CD system in place to have directly the images available after a change

**Review by Bluebugs — DISMISSED** [review]

**Comment by Bluebugs** [comment]
Thanks for the explanation, it makes sense. And yes, setting up fyne-cross-image with a CI/CD would make all of this so much easier to understand.

**Review by Jacalz — DISMISSED** [review]
Looks good. We can release this and then updated to 1.19 once 1.19.2 has been released or something like that :)

**Comment by lucor** [comment]
> We can release this and then updated to 1.19 once 1.19.2 has been released or something like that :)

Fully agree.

Just released the latest version on docker hub.

**Comment by lucor** [comment]
Created https://github.com/fyne-io/fyne-cross/pull/136 to keep track of the 1.19.x images

**Pull request closed without merging**
