### PR TITLE
[base-image] Update Go to v1.17.4 and fyne CLI 2.1.2

### PR DESCRIPTION
**Pull request by lucor**

### CODE REVIEW

**Review by andydotxyz — DISMISSED** [review]

**Comment by Jacalz** [comment]
Should this be rebased and updated to 1.17.2?

**Comment by Jacalz** [comment]
With Go 1.17.3 released today, that might be better to update to :)

**Review by Jacalz — CHANGES_REQUESTED** [review]
With Go 1.17.3 released today, that might be better to update to :)

**Review by Jacalz — APPROVED** [review]
Great stuff. Thanks :)

**Comment by lucor** [comment]
Tagged and released on docker hub:
```
1.1-android-21.12.07
1.1-base-21.12.07
1.1-base-freebsd-21.12.07
1.1-base-llvm-21.12.07
1.1-freebsd-amd64-21.12.07
1.1-freebsd-arm64-21.12.07
1.1-linux-386-21.12.07
1.1-linux-arm-21.12.07
1.1-linux-arm64-21.12.07
1.1-windows-21.12.07
```

**Pull request merged**
