### PR TITLE
Add support for FyneApp.toml

### LINKED ISSUE #78: Add support for FyneApp.toml
### Is your feature request related to a problem? Please describe:
Starting from v2.1.0 Fyne CLI adds a FyneApp.toml metadata file to hold defaults for the package process.
fyne-cross should be updated to support the FyneApp.toml file.

### Is it possible to construct a solution with the existing API?
Yes.

### Describe the solution you'd like to see:
Update fyne-cross to support the FyneApp.toml file out of the box.

### PR DESCRIPTION
**Pull request by lucor**
### Description:

This PR adds support for the  the FyneApp.toml file

Fixes #78

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
I’ll try to have a look at this later in the week once I am done with my exams for this semester.

**Comment by andydotxyz** [comment]
Would it be helpful if we exposed the `FyneApp` structure from `cmd/fyne/` in the main repo?
I think we could probably do that, and possibly even the loader, pretty easily.

**Comment by Jacalz** [comment]
That sounds like it might be a good idea.

**Review by Jacalz — CHANGES_REQUESTED** [review]
Sorry that this took some time. First I had a lot to do, then I forgot about it.

I get this error when trying to build wormhole-gui:
```
[✓] Binary: /home/jacob/Git/wormhole-gui/fyne-cross/bin/darwin-amd64/wormhole-gui
invalid -appVersion parameter, integer and '.' characters only up to x.y.z
[✗] could not package the Fyne app: could not package the Fyne app: exit status 1
make: *** [Makefile:36: darwin] Error 1
```

My FyneApp.toml file looks like this:
```toml
Website = "https://github.com/Jacalz/wormhole-gui"

[Details]
Name = "wormhole-gui"
ID = "io.github.jacalz.wormhole_gui"
Icon = "internal/assets/icon/icon-512.png"
Version = "v3.0.0"
Build = 14
```

**Comment by lucor** [comment]
The fyne CLI tool supports only semantic version. Changing the version to 3.0.0 should work.
With regard to expose the FyneApp would helpful but wondering if it could be a good time to move part of the fyne-cross tool as sub command of the fyne CLI (I'll create a proposal about this) For the moment I'd go for the code duplication instead of expose a new public package that we have to maintain.

**Comment by Jacalz** [comment]
You men that I Seouls drop the "v"? It is part of the test file over at https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/metadata/testdata/FyneApp.toml, which makes me a bit confused.

**Comment by Jacalz** [comment]
I see that it doesn't want the "v" as part of the developer documentation though https://developer.fyne.io/started/metadata. Hmm, strange or I'm just missing something.

**Review by Jacalz — COMMENTED** [review]
Thanks. I get a lot further this time but it fails on building for FreeBSD, it seems.
```
~/go/bin/fyne-cross freebsd -arch amd64,arm64
[i] Target: freebsd/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/jacob/Git/wormhole-gui/fyne-cross/bin/freebsd-amd64
[✓] "dist" dir cleaned: /home/jacob/Git/wormhole-gui/fyne-cross/dist/freebsd-amd64
[✓] "temp" dir cleaned: /home/jacob/Git/wormhole-gui/fyne-cross/tmp/freebsd-amd64
[i] Checking for go.mod: /home/jacob/Git/wormhole-gui/go.mod
[✓] go.mod found
[i] Building binary...
# github.com/go-gl/glfw/v3.3/glfw
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/native_linbsd.go:10:
In file included from /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/glfw/include/GLFW/glfw3native.h:114:
In file included from /freebsd/usr/local/include/GL/glx.h:32:
/freebsd/usr/local/include/GL/gl.h:56:11: warning: 'GLAPIENTRY' macro redefined [-Wmacro-redefined]
/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/glfw/include/GLFW/glfw3.h:5894:10: note: previous definition is here
[✓] Binary: /home/jacob/Git/wormhole-gui/fyne-cross/bin/freebsd-amd64/wormhole-gui
[i] Packaging app...
[✗] rename /home/jacob/Git/wormhole-gui/fyne-cross/tmp/freebsd-amd64/wormhole-gui.tar.xz /home/jacob/Git/wormhole-gui/fyne-cross/dist/freebsd-amd64/wormhole-gui.tar.xz: no such file or directory
make: *** [Makefile:33: freebsd] Error 1
```

**Comment by andydotxyz** [comment]
Is it another OS missing xz support by default?

**Comment by Jacalz** [comment]
I guess it technically could be. Another thing that I noticed was that it seems to want to indent all the detail fields (no longer to the left most edge).
```toml
Website = "https://github.com/Jacalz/wormhole-gui"

[Details]
  Icon = "internal/assets/icon/icon-512.png"
  Name = "wormhole-gui"
  ID = "io.github.jacalz.wormhole_gui"
  Version = "3.0.0"
  Build = 15

```

**Comment by lucor** [comment]
Oh this is weird... tried on my linux box against your latest version on main branch and it worked.

Are you by any chance on a macOS box ? If so could be related to #85

**Comment by Jacalz** [comment]
> Are you by any chance on a macOS box ? If so could be related to #85 

Unfortunately not. I do all of my development on Fedora Linux. This is strange indeed. I am pretty sure it worked when I didn't use this PR, but I don't know what combination of the command and docker image I was using.

**Review by Jacalz — APPROVED** [review]
Sorry for the long wait. It seems that my computer is kind of borked (in more than one way) and didn't want to pull new images. I had been stuck on Go 1.16 images and using an older version of the cli tool. New images were built for https://github.com/fyne-io/fyne-cross/pull/89 and this is now working splendid :)

**Pull request merged**
