### PR TITLE
Fix Android release that generates a .aab file

### PR DESCRIPTION
**Pull request by metal3d**
### Description:

Creating Android release generates a .aab file. The Build() function was working with *.apk files only. So the AAB file was not copied and triggered a SELinux error. The copy sh command also failed.

This commit fixes the problem by changing the pattern to match on copy, and the package name using ".aab" suffix.

NOTE: it could be better to use filepath.Glob() to find files and use os.Rename() instead.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Review by andydotxyz — DISMISSED** [review]
Oh thanks for catching this

**Comment by andydotxyz** [comment]
The failing tests indicate we'll need to update the tested versions to match Fyne...

**Comment by Bluebugs** [comment]
Yes, this require an image release with latest Fyne.

**Comment by Bluebugs** [comment]
Do you mind synchronizing this with latest fyne-cross develop? I think it should be good to merge after that.

**Comment by andydotxyz** [comment]
I have attempted a rebase myself to get this included

**Review by andydotxyz — APPROVED** [review]
All up to date and looking good, thanks

**Pull request merged**
