### PR TITLE
ability to change docker registry

### LINKED ISSUE #150: Being able to set docker registry
When we have our own docker registry mirror and we want to use that instead of dockerhub, we have to set full image name
and there is lots of images that fyne-cross is using so it's good to be able to set dockerhub mirror

Also the bad thing is tag `docker.io` is hardcoded

### PR DESCRIPTION
**Pull request by mhkarimi1383**
### Description:

Added new flag to handle docker registry override

Fixes #150 

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [x] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
Unit tests are getting error where I did nothing

**Comment by andydotxyz** [comment]
The test failures I see (in fact they are compile errors) seem quite correct to me. In many places you have changed type of fields but I can't see why, this is likely the cause.

**Comment by mhkarimi1383** [comment]
Oh
I will check them out
But some of them are from my editor linter

**Comment by mhkarimi1383** [comment]
I reverted the changes in some test files
it should be okay now

**Comment by mhkarimi1383** [comment]
the problem with that error is because of http2/transport.go updates, we have to upgrade the GoLang version or Downgrade related package

If we don't want to upgrade golang version I will downgrade

**Comment by Bluebugs** [comment]
We are not planning to upgrade golang version requirement at this point indeed, so please downgrade for the moment.

**Comment by mhkarimi1383** [comment]
> We are not planning to upgrade golang version requirement at this point indeed, so please downgrade for the moment.

I have downgraded the package now
If it fails I will revert the whole go.sum file

**Review by Bluebugs — APPROVED** [review]

**Pull request merged**
