### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by lucor**
## CLI

- Add support for web target #92
- Add CI job to build calculator app #104 

### Changed

- Bump min Go version to 1.14 to align with Fyne requirements
- Update README for matching modern go command line #114

## Base images (release 22.07.13)

- Add `web` base image
- Update freebsd to v12.3
- Update Go to v1.18.4
- Update Fyne CLI to v2.2.3

The following images have been tagged and released on docker hub for testing:

- fyneio/fyne-cross:1.3-base
- fyneio/fyne-cross:1.3-base-llvm
- fyneio/fyne-cross:1.3-base-freebsd
- fyneio/fyne-cross:1.3-android
- fyneio/fyne-cross:1.3-freebsd-amd64
- fyneio/fyne-cross:1.3-freebsd-arm64
- fyneio/fyne-cross:1.3-linux-386
- fyneio/fyne-cross:1.3-linux-arm64
- fyneio/fyne-cross:1.3-linux-arm
- fyneio/fyne-cross:1.3-web
- fyneio/fyne-cross:1.3-windows

## Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [x] Any breaking changes have a deprecation path or have been discussed.

### CODE REVIEW

**Review by Bluebugs — DISMISSED** [review]
It seems the 1.3 image are not accessible from the github action perspective.

**Comment by lucor** [comment]
Yes, there was a problem building freebsd images due to v12.2 EOL. The freebsd have been updated to v12.3 now, in the upcoming version we should plan to upgrade to 13.x.
Need to double check why the `web` CI is failing but apart that the PR should be ready for testing.

**Comment by andydotxyz** [comment]
Sorry for the Fyne delay, we have v2.2.2 due in 2 days which might be helpful - it has some more cool fixes :)

**Comment by lucor** [comment]
@Jacalz @alexrudd do you have any clue on the `web` CI build failing with permission issues ?
Note: it works correctly locally on a linux host

**Comment by Bluebugs** [comment]
> @Jacalz @alexrudd do you have any clue on the `web` CI build failing with permission issues ? Note: it works correctly locally on a linux host

I am able to reproduce the problem locally with the exact same command line. The issue seems related to the right on the /go directory. If I enable cache outside of the image, things pass. Maybe the right on /go/pkg should be 777 instead.

**Comment by lucor** [comment]
> > @Jacalz @alexrudd do you have any clue on the `web` CI build failing with permission issues ? Note: it works correctly locally on a linux host
> 
> I am able to reproduce the problem locally with the exact same command line. The issue seems related to the right on the /go directory. If I enable cache outside of the image, things pass. Maybe the right on /go/pkg should be 777 instead.

Thanks @Bluebugs . I missed for some reasons the `-no-cache` flag. Fixed in [39f789c](https://github.com/fyne-io/fyne-cross/pull/119/commits/39f789c8d071c339b1fa800b1ae3ad278b3aba39)

**Review by Bluebugs — APPROVED** [review]
Nice work!

**Comment by lucor** [comment]
Updated to Fyne CLI v2.2.2

**Review by Jacalz — COMMENTED** [review]
Sorry for the late review. Should we get the Fyne version updated to v2.2.3 and Go updated to 1.18.4 (supposed to release later today with lots of security fixes)? With that done, I think this looks good.

**Comment by lucor** [comment]
Sure thing. Let's wait for the Go 1.18.4 release, then I'll update the PR.

**Comment by Jacalz** [comment]
1.18.4 has been released. This should be good to go now 🙂

**Review by Jacalz — DISMISSED** [review]
Looks good to me. All images built correctly and built [Rymdport](https://github.com/Jacalz/rymdport) without issues (Android was not tested). I only had time to run the macOS and Linux binaries but everything worked well there as well.

**Review by Bluebugs — CHANGES_REQUESTED** [review]
It seems this is still using go version 1.18.3 in base/Dockerfile.

**Comment by lucor** [comment]
Good catch @Bluebugs, thanks. For some reasons missed to commit that one, anyway the images was built correctly using Go 1.18.4. 
Fixed in [733cb90](https://github.com/fyne-io/fyne-cross/pull/119/commits/733cb9027819c25a2380417dd43c32e589fbe50e)

**Review by Jacalz — APPROVED** [review]

**Review by Bluebugs — APPROVED** [review]
Looks good!

**Pull request merged**
