### PR TITLE
Add engine flag and regression fixes introduced in 1.2.0

### PR DESCRIPTION
**Pull request by lucor**
This PR fixes some regressions introduced with 1.2.0 related to tags and env variable escaping.
Additionally introduces the `--engine` flags that allow to specify the container engine to use between docker and podman. The default behavior is not changed, if the flag is not specified fyne-cross will auto detect the engine.

Fixes: #96, #97

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

**Comment by Jacalz** [comment]
I am getting this error when trying to build the macOS image using this version:
```
[jacob@localhost-live Downloads]$ ~/go/bin/fyne-cross darwin-image -xcode-path Command_Line_Tools_for_Xcode_13.3.dmg 
[i] Building docker darwin image...
[i] Work dir: /tmp/fyne-cross-darwin-build2205463101
[i] Copying the Command Line Tools for Xcode from Command_Line_Tools_for_Xcode_13.3.dmg to /tmp/fyne-cross-darwin-build2205463101/command_line_tools_for_xcode.dmg...
[✓] Command Line Tools for Xcode copied
[✓] Dockerfile created
[i] Building docker image...
[i] macOS SDK: auto
[✗] could not create the docker darwin image: fork/exec : no such file or directory
```
However, I installed the old version and managed to build it using that. I'll then switch to this version again once the image has been built and I test compiling binaries.

**Comment by Jacalz** [comment]
I'm also getting this error when building a macOS binary:
```
[✓] Binary: /home/jacob/Git/rymdport/fyne-cross/bin/darwin-amd64/rymdport
[✓] Package: /home/jacob/Git/rymdport/fyne-cross/dist/darwin-amd64/rymdport.app
[i] Target: darwin/arm64
[i] Cleaning target directories...
[✓] "dist" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/dist/darwin-arm64
[✓] "temp" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/tmp/darwin-arm64
[✓] "bin" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/bin/darwin-arm64
[i] Checking for go.mod: /home/jacob/Git/rymdport/go.mod
[✓] go.mod found
[i] Packaging app...
[i] Building binary...
# runtime/cgo
ld64.lld: warning: ignoring unknown argument: -platform_version
ld64.lld: warning: ignoring unknown argument: -w
ld64.lld: warning: ignoring unknown argument: -s
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
ld64.lld: error: Unable to find framework for -framework CoreFoundation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[✗] exit status 2
make: *** [Makefile:36: darwin] Error 1
```

**Comment by Jacalz** [comment]
That darwin image was created with the old version of fyne-cross (release 1.2.0). I don't know if that makes a difference?

**Comment by lucor** [comment]
That should not make difference. The issue fixed in [e86c40f](https://github.com/fyne-io/fyne-cross/pull/99/commits/e86c40fb7e4543da3666bb3f76713097a22ca559) was due to how the env variable was passed to docker/podman.
To allow a correct parsing the key/value pair should be double quoted like  `-e "CGO_CFLAGS=-mmacosx-version-min=11.1"`

**Comment by Jacalz** [comment]
Thanks. I'll just build the binaries and then test the Windows binary to make sure that no terminal is spawned.

**Comment by Jacalz** [comment]
One last error it seems:
```
~/go/bin/fyne-cross windows -arch amd64
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /home/jacob/Git/rymdport/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /home/jacob/Git/rymdport/go.mod
[✓] go.mod found
[i] Building binary...
# github.com/Jacalz/rymdport/v3
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option '-mwindows'; did you mean '-m3dnow'?
```

**Comment by lucor** [comment]
ok, it looks like the env var need be quoted only if the value contains the `=` char... :)
Fixed in [a927c39](https://github.com/fyne-io/fyne-cross/pull/99/commits/a927c397a36416e7690078fc25443f8bd6934ad1)

**Comment by Jacalz** [comment]
It seems like one fix leads to another error somewhere else :(
```
[i] Building binary...
# runtime/cgo
/usr/bin/ld: /freebsd/usr/lib/crt1.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /freebsd/usr/lib/crt1.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /freebsd/usr/lib/crt1.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /freebsd/usr/lib/crt1.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /freebsd/usr/lib/crt1.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /freebsd/usr/lib/crt1.o: error adding symbols: file in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[✗] exit status 2
```

**Comment by lucor** [comment]
It looks like freebsd compilation is the only one does not like the double quotes... updated in [3e59801](https://github.com/fyne-io/fyne-cross/pull/99/commits/3e59801d3ddb2f77b87079d8f78da68f71cdb66c)

**Review by Jacalz — APPROVED** [review]
Works great now. Thanks :)

**Comment by Jacalz** [comment]
I realised that I got too carried away with other issues that I never tested multiple build tags. It might be good if you hold off with merging until I’ve tested that tomorrow :)

**Comment by lucor** [comment]
Great, thanks @Jacalz  for the help with testing!

**Comment by lucor** [comment]
> I realised that I got too carried away with other issues that I never tested multiple build tags. It might be good if you hold off with merging until I’ve tested that tomorrow :)

I'm so sorry, I've missed your message and merged into develop :-(
Anyway I'll wait to create a PR release for the new version waiting for your feedback about the tags.

**Comment by Jacalz** [comment]
No worries. I’ll just check it out then instead :)

**Pull request merged**
